package com.example.day_00_lainxi.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day_00_lainxi.bean.DataDao;

import com.example.day_00_lainxi.dao.DataDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoDaoConfig;

    private final DataDaoDao dataDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoDaoConfig = daoConfigMap.get(DataDaoDao.class).clone();
        dataDaoDaoConfig.initIdentityScope(type);

        dataDaoDao = new DataDaoDao(dataDaoDaoConfig, this);

        registerDao(DataDao.class, dataDaoDao);
    }
    
    public void clear() {
        dataDaoDaoConfig.clearIdentityScope();
    }

    public DataDaoDao getDataDaoDao() {
        return dataDaoDao;
    }

}
